### ISSUE TITLE
Error starting debugger after migration from 2.3.141 to RELEASE

### ISSUE THREAD

**Issue by saskenuba** [jpmonettas/flow-storm-debugger#50]
Thanks for the tool, it became my default debugger that starts along my project  :)

After migrating to the latest version I can't start the debugger anymore. My best guess is that flow-storm calls something for cljs, which doesn't make sense since my project is Clojure only.

Version 2.3.141 works as usual.

My stack is: 
Clojure 1.10.3
17.0.2-tem

```edn
{:extra-deps {nrepl/nrepl                   {:mvn/version "1.0.0"}
                cider/cider-nrepl             {:mvn/version "0.28.5"}
                refactor-nrepl/refactor-nrepl {:mvn/version "3.5.5"}}
```

When starting the debugger the following is shown:
```
Syntax error (NoSuchMethodError) compiling at (flow_storm/runtime/debuggers_api.cljc:1:1).
'java.util.stream.Collector com.google.common.collect.ImmutableSortedSet.toImmutableSortedSet(java.util.Comparator)'
```

Complete stack trace:
```
ERROR: Unhandled REPL handler exception processing message {:op stacktrace, :nrepl.middleware.print/stream? 1, :nrepl.middleware.print/print cider.nrepl.pprint/pprint, :nrepl.middleware.print/quota 1048576, :nrepl.middleware.print/buffer-size 4096, :nrepl.middleware.print/options {:right-margin 80}, :session b6183f08-b490-4972-a649-6117146f0761, :id 15}
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.google.javascript.jscomp.deps.ModuleLoader
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at clojure.core$deref_future.invokeStatic(core.clj:2304)
	at clojure.core$future_call$reify__8477.deref(core.clj:6976)
	at clojure.core$deref.invokeStatic(core.clj:2324)
	at clojure.core$pmap$step__8490$fn__8494.invoke(core.clj:7027)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.LazySeq.first(LazySeq.java:73)
	at clojure.lang.RT.first(RT.java:692)
	at clojure.core$first__5401.invokeStatic(core.clj:55)
	at clojure.core$first__5401.invoke(core.clj:55)
	at cider.nrepl.middleware.stacktrace$flag_duplicates.invokeStatic(stacktrace.clj:198)
	at cider.nrepl.middleware.stacktrace$flag_duplicates.invoke(stacktrace.clj:194)
	at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invokeStatic(stacktrace.clj:219)
	at cider.nrepl.middleware.stacktrace$analyze_stacktrace.invoke(stacktrace.clj:213)
	at cider.nrepl.middleware.stacktrace$analyze_cause.invokeStatic(stacktrace.clj:323)
	at cider.nrepl.middleware.stacktrace$analyze_cause.invoke(stacktrace.clj:314)
	at cider.nrepl.middleware.stacktrace$analyze_causes$fn__6288.invoke(stacktrace.clj:348)
	at clojure.core$map$fn__5880$fn__5881.invoke(core.clj:2746)
	at clojure.core$take_while$fn__5931$fn__5932.invoke(core.clj:2905)
	at clojure.lang.Iterate.reduce(Iterate.java:81)
	at clojure.core$transduce.invokeStatic(core.clj:6885)
	at clojure.core$into.invokeStatic(core.clj:6901)
	at clojure.core$into.invoke(core.clj:6889)
	at cider.nrepl.middleware.stacktrace$analyze_causes.invokeStatic(stacktrace.clj:347)
	at cider.nrepl.middleware.stacktrace$analyze_causes.invoke(stacktrace.clj:339)
	at cider.nrepl.middleware.stacktrace$handle_stacktrace.invokeStatic(stacktrace.clj:356)
	at cider.nrepl.middleware.stacktrace$handle_stacktrace.invoke(stacktrace.clj:353)
	at clojure.lang.Var.invoke(Var.java:388)
	at cider.nrepl$wrap_stacktrace$fn__3379.invoke(nrepl.clj:432)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.middleware.load_file$wrap_load_file$fn__1866.invoke(load_file.clj:81)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.middleware.caught$wrap_caught$fn__1257.invoke(caught.clj:97)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.middleware.dynamic_loader$wrap_dynamic_loader$fn__1510.invoke(dynamic_loader.clj:98)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.middleware.lookup$wrap_lookup$fn__1910.invoke(lookup.clj:52)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_content_type$fn__3239.invoke(nrepl.clj:107)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.middleware.print$wrap_print$fn__1224.invoke(print.clj:234)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.middleware.completion$wrap_completion$fn__1834.invoke(completion.clj:58)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_slurp$fn__3247.invoke(nrepl.clj:121)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_xref$fn__3429.invoke(nrepl.clj:514)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_resource$fn__3363.invoke(nrepl.clj:406)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_undef$fn__3411.invoke(nrepl.clj:493)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_tracker$fn__3403.invoke(nrepl.clj:482)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_ns$fn__3331.invoke(nrepl.clj:300)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at cider.nrepl$wrap_complete$fn__3271.invoke(nrepl.clj:143)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.middleware.session$session$fn__1427.invoke(session.clj:325)
	at nrepl.middleware$wrap_conj_descriptor$fn__988.invoke(middleware.clj:16)
	at nrepl.server$default_handler$fn__1995.invoke(server.clj:141)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:24)
	at nrepl.server$handle_STAR_.invoke(server.clj:21)
	at nrepl.server$handle$fn__1963.invoke(server.clj:41)
	at clojure.core$binding_conveyor_fn$fn__5772.invoke(core.clj:2034)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.javascript.jscomp.deps.ModuleLoader
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.Compiler.maybeResolveIn(Compiler.java:7442)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4358)
	at clojure.core$ns_resolve.invokeStatic(core.clj:4347)
	at clojure.core$ns_resolve.invoke(core.clj:4347)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java$resolve_class$fn__5388.invoke(java.clj:301)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java$resolve_class.invokeStatic(java.clj:301)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java$resolve_class.invoke(java.clj:295)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java$resolve_symbol.invokeStatic(java.clj:335)
	at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java$resolve_symbol.invoke(java.clj:321)
	at cider.nrepl.middleware.stacktrace$analyze_fn.invokeStatic(stacktrace.clj:82)
	at cider.nrepl.middleware.stacktrace$analyze_fn.invoke(stacktrace.clj:61)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at clojure.core$comp$fn__5825.invoke(core.clj:2573)
	at cider.nrepl.middleware.stacktrace$analyze_frame.invokeStatic(stacktrace.clj:211)
	at cider.nrepl.middleware.stacktrace$analyze_frame.invoke(stacktrace.clj:207)
	at clojure.core$partial$fn__5857.invoke(core.clj:2628)
	at clojure.core$pmap$fn__8485$fn__8486.invoke(core.clj:7024)
	... 6 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableSortedSet.toImmutableSortedSet(java.util.Comparator)' [in thread "nREPL-session-b6183f08-b490-4972-a649-6117146f0761"]
	at com.google.javascript.jscomp.deps.ModuleLoader.createRootPaths(ModuleLoader.java:257)
	at com.google.javascript.jscomp.deps.ModuleLoader.<init>(ModuleLoader.java:147)
	at com.google.javascript.jscomp.deps.ModuleLoader.<init>(ModuleLoader.java:48)
	at com.google.javascript.jscomp.deps.ModuleLoader$Builder.build(ModuleLoader.java:139)
	at com.google.javascript.jscomp.deps.ModuleLoader.<clinit>(ModuleLoader.java:408)
	at com.google.javascript.jscomp.DiagnosticGroups.<clinit>(DiagnosticGroups.java:182)
	at cljs.closure__init.load(Unknown Source)
	at cljs.closure__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at cljs.repl$loading__6706__auto____1381.invoke(repl.cljc:9)
	at cljs.repl__init.load(Unknown Source)
	at cljs.repl__init.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:495)
	at java.base/java.lang.Class.forName(Class.java:474)
	at clojure.lang.RT.classForName(RT.java:2212)
	at clojure.lang.RT.classForName(RT.java:2221)
	at clojure.lang.RT.loadClassForName(RT.java:2240)
	at clojure.lang.RT.load(RT.java:449)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:2088)
	at flow_storm.runtime.debuggers_api$eval51255$loading__6737__auto____51257.invoke(debuggers_api.cljc:1)
	at flow_storm.runtime.debuggers_api$eval51255.invokeStatic(debuggers_api.cljc:1)
	at flow_storm.runtime.debuggers_api$eval51255.invoke(debuggers_api.cljc:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.invoke(RestFn.java:1289)
	at flow_storm.api$eval48457$loading__6737__auto____48458.invoke(api.clj:1)
	at flow_storm.api$eval48457.invokeStatic(api.clj:1)
	at flow_storm.api$eval48457.invoke(api.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7170)
	at clojure.lang.Compiler.load(Compiler.java:7640)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:459)
	at clojure.lang.RT.load(RT.java:424)
	at clojure.core$load$fn__6856.invoke(core.clj:6115)
	at clojure.core$load.invokeStatic(core.clj:6114)
	at clojure.core$load.doInvoke(core.clj:6098)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5897)
	at clojure.core$load_one.invoke(core.clj:5892)
	at clojure.core$load_lib$fn__6796.invoke(core.clj:5937)
	at clojure.core$load_lib.invokeStatic(core.clj:5936)
	at clojure.core$load_lib.doInvoke(core.clj:5917)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$load_libs.invokeStatic(core.clj:5974)
	at clojure.core$load_libs.doInvoke(core.clj:5958)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$require.invokeStatic(core.clj:5996)
	at clojure.core$require.doInvoke(core.clj:5996)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$serialized_require.invokeStatic(core.clj:6068)
	at clojure.core$requiring_resolve.invokeStatic(core.clj:6077)
	at clojure.core$requiring_resolve.invoke(core.clj:6071)
	at user$start_debugger.invokeStatic(user.clj:41)
	at user$start_debugger.invoke(user.clj:40)
	at user$eval48450.invokeStatic(NO_SOURCE_FILE:42)
	at user$eval48450.invoke(NO_SOURCE_FILE:42)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.eval(Compiler.java:7136)
	at clojure.core$eval.invokeStatic(core.clj:3202)
	at clojure.core$eval.invoke(core.clj:3198)
	at nrepl.middleware.interruptible_eval$evaluate$fn__1291$fn__1292.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1977)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1977)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at nrepl.middleware.interruptible_eval$evaluate$fn__1291.invoke(interruptible_eval.clj:87)
	at clojure.main$repl$read_eval_print__9110$fn__9113.invoke(main.clj:437)
	at clojure.main$repl$read_eval_print__9110.invoke(main.clj:437)
	at clojure.main$repl$fn__9119.invoke(main.clj:458)
	at clojure.main$repl.invokeStatic(main.clj:458)
	at clojure.main$repl.doInvoke(main.clj:368)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:84)
	at nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:56)
	at nrepl.middleware.interruptible_eval$interruptible_eval$fn__1324$fn__1328.invoke(interruptible_eval.clj:152)
	at clojure.lang.AFn.run(AFn.java:22)
	at nrepl.middleware.session$session_exec$main_loop__1394$fn__1398.invoke(session.clj:218)
	at nrepl.middleware.session$session_exec$main_loop__1394.invoke(session.clj:217)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 more
```

Thanks!

**Comment by jpmonettas** [comment]
Hmm weird, I think some dependency is conflicting with it :thinking: . How are you running it? Can you run it on a empty folder, with no deps?

**Comment by danielsz** [comment]
Correct, it seems to be a dependency conflict, namely Guava. I've seen this too.
@jpmonettas you are requiring mount which is requiring datomic-free which is pulling in a very old version of guava.

**Comment by danielsz** [comment]
Not sure why cli -Stree doesn't show it, but I use different tooling and I can see it. Also, it's declared in mount's [project.clj](https://github.com/tolitius/mount/blob/b77f504cfdedd143cfb7b333ebc6ceaff06e0fba/project.clj#L28) file.

**Comment by jpmonettas** [comment]
Hmm that is weird, they are under dev dependencies 🤔  but I also see them on the pom.
I don't think mount intention is to contain all those deps.

**Comment by jpmonettas** [comment]
@danielsz ok I figured out asking on clojurians slack. Those aren't packaged inside mount, they are in the pom with `provided` scope. I think the tool you are using isn't filtering `compiled` scope, which is what will end up in the classpath

**Comment by danielsz** [comment]
That is true. They end up in the maven `prodived` scope. So this may not be the culprit. Still, something weird is going on. Guava is also used in the google-closure project, introduced by Clojurescript.

**Comment by jpmonettas** [comment]
@danielsz I don't see ClojureScript nor the google-closure-library pulling  guava.
This is the clojurescript tree :
```
org.clojure/clojurescript 1.11.57
  . com.google.javascript/closure-compiler-unshaded v20220502
  . org.clojure/google-closure-library 0.0-20211011-0726fdeb
    . org.clojure/google-closure-library-third-party 0.0-20211011-0726fdeb
  . org.clojure/tools.reader 1.3.6
  . com.cognitect/transit-java 1.0.362
    . com.fasterxml.jackson.core/jackson-core 2.8.7
    . org.msgpack/msgpack 0.6.12
      . com.googlecode.json-simple/json-simple 1.1.1
      . org.javassist/javassist 3.18.1-GA
    . javax.xml.bind/jaxb-api 2.3.0

``` 
What I have seen in the past is old guava dependency (because of dtype-next for example) conflicting with ClojureScript, but for a different reason.

**Comment by danielsz** [comment]
Clojurescript requires the closure-compiler-unshaded jar which ships dependencies such as Guava, etc. This seems to be a [topic](https://github.com/google/closure-compiler/issues/3896) of debate on the tickets. I'm not clearheaded as to whether this has any bearing on the issue at hand.

**Comment by danielsz** [comment]
It looks like @thheller added an explicit [dependency](https://github.com/thheller/shadow-cljs/commit/c03364b6be69792e8f1bdb3d197bf256db1c9c4d) on the latest Guava in Shadow-cljs as a temporary fix, to counter the effects of the google-closure's shady business (pun intended).

**Comment by jpmonettas** [comment]
This commit should fix the issue https://github.com/jpmonettas/flow-storm-debugger/commit/eda9c04237cd947fff43861c15197458165683fd

Now flow-storm doesn't have a hard dependency on ClojureScript, and will not pull it.
When used in ClojureScript it assumes the compiler is there and will lazy load its functions.

**Comment by danielsz** [comment]
Awesome. Thank you!
